const std = @import("std");

const Token = @This();

kind: Kind,
// todo : we might be able to cram the range into a u64 using the first 32 bits
//  for the start and the last 32 for the end
start: usize,
end: usize,

pub const Kind = enum {
    unknown,
    eof,

    at,
    pound,
    dollar,
    l_paren,
    r_paren,
    l_brace,
    r_brace,
    l_bracket,
    r_bracket,
    backslash,
    semicolon,
    colon,
    single_quote,
    double_quote,
    comma,
    period,
    question,

    // operators
    // todo : wrapping and saturating ops
    equal,
    equal_equal,
    plus,
    plus_equal,
    minus,
    minus_equal,
    asterisk,
    asterisk_equal,
    slash,
    slash_equal,
    percent,
    percent_equal,
    ampersand,
    ampersand_ampersand,
    ampersand_equal,
    pipe,
    pipe_pipe,
    pipe_equal,
    caret,
    carat_equal,
    tilde,
    tilde_equal,
    bang,
    bang_equal,
    l_angled,
    l_angled_angled,
    l_angled_equal,
    l_angled_angled_equal,
    r_angled,
    r_angled_angled,
    r_angled_equal,
    r_angled_angled_equal,

    arrow,
    range,
    range_inclusive,

    // container tokens (their raw values matter)
    identifier,
    builtin,
    string,
    char,
    int_literal,
    float_literal,

    // keywords
    true,
    false,
    @"pub",
    @"inline",
    @"fn",
    ret,
    @"const",
    @"struct",
    @"union",
    @"enum",
    let,
    mut,
    @"if",
    @"switch",
    @"else",
    @"while",
    @"for",
    loop,
    @"defer",
    in,
    @"break",
    @"continue",
};

pub const longest_symbol = blk: {
    var max: usize = 0;
    for (symbol_map.keys()) |k| {
        max = @max(max, k.len);
    }
    break :blk max;
};

pub const symbol_map = std.StaticStringMap(Kind).initComptime(.{
    .{"@", .at},
    .{"#", .pound},
    .{"$", .dollar},
    .{"(", .l_paren},
    .{")", .r_paren},
    .{"{", .l_brace},
    .{"}", .r_brace},
    .{"[", .l_bracket},
    .{"]", .r_bracket},
    .{"\\", .backslash},
    .{";", .semicolon},
    .{":", .colon},
    .{"'", .single_quote},
    .{"\"", .double_quote},
    .{",", .comma},
    .{".", .period},
    .{"?", .question},
    .{"=", .equal},
    .{"==", .equal_equal},
    .{"+", .plus},
    .{"+=", .plus_equal},
    .{"-", .minus},
    .{"-=", .minus_equal},
    .{"*", .asterisk},
    .{"*=", .asterisk_equal},
    .{"/", .slash},
    .{"/=", .slash_equal},
    .{"%", .percent},
    .{"%=", .percent_equal},
    .{"&", .ampersand},
    .{"&&", .ampersand_ampersand},
    .{"&=", .ampersand_equal},
    .{"|", .pipe},
    .{"||", .pipe_pipe},
    .{"|=", .pipe_equal},
    .{"^", .carat},
    .{"^=", .carat_equal},
    .{"~", .tilde},
    .{"~=", .tilde_equal},
    .{"!", .bang},
    .{"!=", .bang_equal},
    .{"<", .l_angled},
    .{"<=", .l_angled_equal},
    .{">", .r_angled},
    .{">=", .r_angled_equal},
    .{"<<", .l_angled_angled},
    .{"<<=", .l_angled_angled_equal},
    .{">>", .r_angled_angled},
    .{">>=", .r_angled_angled_equal},
    .{"->", .arrow},
    .{"..", .range},
    .{"..=", .range_inclusive},
});

/// a map from string representations of keywords,
/// to their respective TokenType
pub const keyword_map = std.StaticStringMap(Kind).initComptime(.{
    .{"true", .true},
    .{"false", .false},
    .{"pub", .@"pub"},
    .{"inline", .@"inline"},
    .{"fn", .@"fn"},
    .{"ret", .ret},
    .{"const", .@"const"},
    .{"struct", .@"struct"},
    .{"union", .@"union"},
    .{"enum", .@"enum"},
    .{"let", .let},
    .{"mut", .mut},
    .{"if", .@"if"},
    .{"switch", .@"switch"},
    .{"else", .@"else"},
    .{"while", .@"while"},
    .{"for", .@"for"},
    .{"loop", .loop},
    .{"defer", .@"defer"},
    .{"in", .in},
    .{"break", .@"break"},
    .{"continue", .@"continue"},
});

pub fn getKeyword(bytes: []const u8) ?Kind {
    return keyword_map.get(bytes);
}

pub fn lexeme(kind: Token.Kind) ?[]const u8 {
    return switch (kind) {
        // keywords
        .@"break",
        .@"const",
        .@"continue",
        .@"defer",
        .@"else",
        .@"enum",
        .@"fn",
        .@"for",
        .@"if",
        .@"inline",
        .@"pub",
        .@"struct",
        .@"switch",
        .@"union",
        .@"while",
        .false,
        .in,
        .let,
        .loop,
        .mut,
        .ret,
        .true => |t| @tagName(t),

        // symbols
        .at => "@",
        .pound => "#",
        .dollar => "$",
        .l_paren => "(",
        .r_paren => ")",
        .l_brace => "{",
        .r_brace => "}",
        .l_bracket => "[",
        .r_bracket => "]",
        .backslash => "\\",
        .semicolon => ";",
        .colon => ":",
        .single_quote => "'",
        .double_quote => "\"",
        .comma => ",",
        .period => ".",
        .question => "?",
        .equal => "=",
        .equal_equal => "==",
        .plus => "+",
        .plus_equal => "+=",
        .minus => "-",
        .minus_equal => "-=",
        .asterisk => "*",
        .asterisk_equal => "*=",
        .slash => "/",
        .slash_equal => "/=",
        .percent => "%",
        .percent_equal => "%=",
        .ampersand => "&",
        .ampersand_ampersand => "&&",
        .ampersand_equal => "&=",
        .pipe => "|",
        .pipe_pipe => "||",
        .pipe_equal => "|=",
        .caret => "^",
        .carat_equal => "^=",
        .tilde => "~",
        .tilde_equal => "~=",
        .bang => "!",
        .bang_equal => "!=",
        .l_angled => "<",
        .l_angled_equal => "<=",
        .r_angled => ">",
        .r_angled_equal => ">=",
        .l_angled_angled => "<<",
        .l_angled_angled_equal => "<<=",
        .r_angled_angled => ">>",
        .r_angled_angled_equal => ">>=",
        .arrow => "->",
        .range => "..",
        .range_inclusive => "..=",

        .char,
        .eof,
        .identifier,
        .builtin,
        .int_literal,
        .float_literal,
        .string,
        .unknown => null,
    };
}
